[CI] Update to deploy commands for prod/stg
layer5labs/meshery-extensions-packages pull request #108
Opened 2023-07-13 19:54 UTC by theBeginner86

**Description**

Currently, we are using separate deploy cmds for our 2 systems: server, kratos, and hydra.
We do have a single make target but we are not making use of it. Event though the single make target does the exact same job of running the individual targets for each system.

This PR updates it to the usage of single target.
This would ensure that the recent addition of db target is also called.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-07-13 19:55 UTC, theBeginner86 commented
I can't recall why we moved to individual targets or it was like this from beginning and we missed updating this workflow 🤔

2023-07-17 08:54 UTC, MUzairS15 requested changes

2023-07-17 08:54 UTC, MUzairS15 commented on .github/workflows/meshery-cloud-release.yml
> +          sudo make-stg-deploy
```suggestion
          sudo make stg-deploy
```

2023-07-17 08:55 UTC, MUzairS15 approved these changes

2023-07-17 08:55 UTC, merged