feat: add helm plugin to import helm chart
layer5labs/meshery-extensions-packages pull request #304
Opened 2024-08-30 13:51 UTC by Aijeyomah

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-09-09 18:13 UTC, leecalcote commented
@Aijeyomah be sure to signoff on your commits.

2024-09-10 09:54 UTC, MUzairS15 commented
@Aijeyomah If you have the helm-plugin ready (except the emailing part), then let’s publish the initial version of it.
We can add the email support in next iteration.

2024-09-10 13:44 UTC, leecalcote commented
@Aijeyomah, if I may redirect you one more time… do you mind making this PR on the kanvas-snapshot repo?

2024-09-10 13:58 UTC, MUzairS15 requested changes

2024-09-10 13:58 UTC, MUzairS15 commented on helm-plugins/snapshot/main.go
> +		GithubToken:         os.Getenv("GITHUB_TOKEN"),
@Aijeyomah Instead of using the ENV variables, we can inject the values at build time.

2024-09-10 13:58 UTC, MUzairS15 commented on helm-plugins/snapshot/main.go
> +	if *chartURI == "" {
PLease add nil check.

2024-09-10 13:58 UTC, MUzairS15 commented on helm-plugins/snapshot/main.go
> +		log.Fatalf("Failed to load .env file: %s", err)
Please use `meshkit logger` and `meshkit error`https://docs.meshery.io/project/contributing/contributing-error

2024-09-10 13:58 UTC, MUzairS15 commented on helm-plugins/snapshot/plugin.yaml
> +    # No need to manually install here since Helm manages this.
@Aijeyomah How does this work? Shouldn't we need to download the binary (the go program) and place it in the "HELM_PLUGIN_DIR/bin"?

2024-09-12 20:02 UTC, leecalcote commented
Please relocate PR...

2024-09-12 23:15 UTC, closed without merging