Package extension as part of `Kanvas build and rollout`
layer5labs/meshery-extensions-packages pull request #327
Opened 2024-09-27 11:59 UTC by MUzairS15

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2024-09-27 12:08 UTC, MUzairS15 commented
This will ensure every time Meshery gets released, extensions are bundled with the Kanvas deployment image.

If we want, the Kanvas deployment should be updated for every independent `Kanvas` release (i.e., for every revision of Kanvas), we must use a different image tag, otherwise rollout command will not update the deployment.

Commit Sha? or version of Extension itself? (v0.7.108-2/-3...)

2024-09-27 23:14 UTC, leecalcote requested changes

2024-09-27 23:14 UTC, leecalcote commented on .github/workflows/build-and-deploy-meshery-extensions-playground.yml
> +
The Docker-published GitHub Actions are much more full-featured and are quite reliable. Can we switch to them?

Use the multi-platform workflow as an example, please.

2024-09-30 19:04 UTC, leecalcote approved these changes

2024-09-30 19:04 UTC, merged